import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./compunents/Navbar"; // Adjust path based on folder structure
import Footer from "./compunents/Footer"; // Adjust path based on folder structure
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* Navbar will render at the top */}
        <main>{children}</main> {/* Content from individual pages */}
       <Footer /> {/* Footer will render at the bottom */}
      </body>
    </html>
  );
}
